# Generated by Django 5.2.2 on 2025-06-04 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_name', models.CharField(help_text='Standard SFLF column name', max_length=255)),
                ('synonym', models.CharField(help_text='Alternative column name', max_length=255)),
            ],
            options={
                'unique_together': {('standard_name', 'synonym')},
            },
        ),
        migrations.CreateModel(
            name='FOIAUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='outputs/')),
                ('processing_mode', models.CharField(choices=[('manual', 'Manual'), ('ai_assist', 'AI Assist')], default='manual', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('openai', 'OpenAI Request')], max_length=20)),
                ('message', models.TextField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='normalizer.foiaupload')),
            ],
        ),
        migrations.CreateModel(
            name='StatusSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_status', models.CharField(help_text='Standard SFLF status', max_length=255)),
                ('synonym', models.CharField(help_text='Alternative status name', max_length=255)),
            ],
            options={
                'unique_together': {('standard_status', 'synonym')},
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_column', models.CharField(max_length=255)),
                ('mapped_column', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, help_text='AI confidence score', null=True)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='normalizer.foiaupload')),
            ],
            options={
                'unique_together': {('upload', 'original_column')},
            },
        ),
        migrations.CreateModel(
            name='StatusMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(max_length=255)),
                ('mapped_status', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, help_text='AI confidence score', null=True)),
                ('user_confirmed', models.BooleanField(default=False)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_mappings', to='normalizer.foiaupload')),
            ],
            options={
                'unique_together': {('upload', 'original_status')},
            },
        ),
    ]
