# Generated by Django 5.2.2 on 2025-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foiaupload',
            name='agency',
            field=models.CharField(blank=True, help_text='Associated federal, state or local agency', max_length=255),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='source',
            field=models.TextField(blank=True, help_text='Where the FOIA log was obtained (URL or description)'),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='time_period_end',
            field=models.DateField(blank=True, help_text='End date of log period', null=True),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='time_period_start',
            field=models.DateField(blank=True, help_text='Start date of log period', null=True),
        ),
    ]
