# Generated by Django 4.2.7 on 2025-06-14 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('normalizer', '0002_foiaupload_agency_foiaupload_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('submissions_count', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('rejected_count', models.IntegerField(default=0)),
                ('last_submission', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-approved_count', '-submissions_count'],
            },
        ),
        migrations.RemoveField(
            model_name='foiaupload',
            name='processing_mode',
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='submission_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='submitter_email',
            field=models.EmailField(blank=True, help_text='Optional email (kept private)', max_length=254),
        ),
        migrations.AddField(
            model_name='foiaupload',
            name='submitter_username',
            field=models.CharField(blank=True, help_text='Optional username for attribution', max_length=100),
        ),
    ]
